use chrono::Utc;
use jsonwebtoken::{decode, encode, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Claims {
    #[serde(rename = "userId")]
    pub user_id: String,
    pub iat: i64,
    pub exp: i64,
}

const DAY: i64 = 24 * 60 * 60;
/// Same as Node's `expiresIn: '7d'` for user tokens.
pub const USER_TOKEN_DAYS: i64 = 7;
/// Same as Node's `expiresIn: '3650d'` for bot tokens.
pub const BOT_TOKEN_DAYS: i64 = 3650;

pub fn sign(user_id: &str, secret: &str, days: i64) -> String {
    let now = Utc::now().timestamp();
    let claims = Claims {
        user_id: user_id.to_string(),
        iat: now,
        exp: now + days * DAY,
    };
    encode(
        &Header::default(),
        &claims,
        &EncodingKey::from_secret(secret.as_bytes()),
    )
    .expect("JWT signing cannot fail with HS256")
}

/// Verifies an HS256 token and returns the userId, or None if invalid/expired.
pub fn verify(token: &str, secret: &str) -> Option<String> {
    let mut validation = Validation::default();
    // jsonwebtoken requires `exp` by default, same as Node checks it.
    validation.validate_exp = true;
    decode::<Claims>(
        token,
        &DecodingKey::from_secret(secret.as_bytes()),
        &validation,
    )
    .ok()
    .map(|data| data.claims.user_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SECRET: &str = "akami-wtf-secret-key-12345";
    // Generated by Node `jsonwebtoken` with the same secret (exp in 2036).
    const NODE_TOKEN: &str = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ0ZXN0LXVzZXItMTIzIiwiaWF0IjoxNzg0NTg0MzE5LCJleHAiOjIwOTk5NDQzMTl9.E7_7zzF-AcyWhd5Qz_tCULWSTCyVhxGcrm9RB7uiX-8";

    #[test]
    fn verifies_node_issued_token() {
        assert_eq!(verify(NODE_TOKEN, SECRET), Some("test-user-123".into()));
    }

    #[test]
    fn rejects_wrong_secret() {
        assert_eq!(verify(NODE_TOKEN, "wrong"), None);
    }

    #[test]
    fn roundtrip() {
        let token = sign("u1", SECRET, USER_TOKEN_DAYS);
        assert_eq!(verify(&token, SECRET), Some("u1".into()));
    }

    #[test]
    fn bcrypt_verifies_bcryptjs_hash() {
        // Hash produced by Node bcryptjs (cost 10), as stored in dev.db.
        let node_hash = "$2b$10$Ms3k62NdGWmOM9ZGldZxsOTdcZZfIQ4iNl03gcuN800/uQaxlEt3a";
        assert!(bcrypt::verify("пароль-test-123", node_hash).unwrap());
        assert!(!bcrypt::verify("wrong", node_hash).unwrap());

        // And our own hashes use the same cost so bcryptjs can read them back.
        let ours = bcrypt::hash("пароль-test-123", 10).unwrap();
        assert!(ours.starts_with("$2b$10$"));
    }
}
